"use client";

import * as React from "react";
import { Clock } from "lucide-react";
import {
  formatDate,
  formatDuration,
  formatTime,
} from "@/lib/selectors";
import type { Student, TimeLog } from "@/lib/types";

// ============================================================
// Weekly grouping helper
// ============================================================

/** Returns the ISO date (yyyy-mm-dd) of the Monday of the week containing `iso`. */
function weekKey(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "1970-01-05"; // Monday epoch fallback
  const day = d.getDay();
  const diff = day === 0 ? -6 : 1 - day; // shift Sunday(0) to previous Monday
  const monday = new Date(d);
  monday.setDate(d.getDate() + diff);
  return monday.toISOString().slice(0, 10);
}

/** Human label for a week-key, e.g. "Week of Jun 16, 2025". */
function weekLabelFromKey(key: string): string {
  const d = new Date(key);
  if (Number.isNaN(d.getTime())) return "";
  return `Week of ${d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  })}`;
}

export interface StudentTimeReportRow {
  student: Student;
  companyName?: string;
  supervisorName?: string;
  sessions: TimeLog[];
}

interface TimeLogReportDocumentProps {
  title: string;
  /** Shown under the title in the header. */
  subtitle?: string;
  rows: StudentTimeReportRow[];
  /** Cohort-wide summary (shown in the header stats box). If omitted, derived from rows. */
  summaryStats?: { label: string; value: string }[];
}

/**
 * Print-styled Time Log Report document. Renders inside a `PdfPreviewModal`.
 * Each student gets: header (name/number/course/company), summary stats,
 * and a session table grouped by week with subtotal rows + a grand total.
 */
export function TimeLogReportDocument({
  title,
  subtitle,
  rows,
  summaryStats,
}: TimeLogReportDocumentProps) {
  const generatedLabel = formatDate(new Date().toISOString());

  // Cohort-wide derived stats
  const totalSessions = rows.reduce((s, r) => s + r.sessions.length, 0);
  const totalMs = rows.reduce(
    (s, r) =>
      s +
      r.sessions.reduce(
        (ms, t) => ms + (t.durationMs ?? 0),
        0
      ),
    0
  );
  const studentCount = rows.length;

  const derivedStats = summaryStats ?? [
    { label: "Students", value: String(studentCount) },
    { label: "Total Sessions", value: String(totalSessions) },
    { label: "Total Tracked", value: formatDuration(totalMs) },
  ];

  return (
    <div className="space-y-5 text-slate-900">
      {/* Header */}
      <div className="border-b border-slate-300 pb-3">
        <h1 className="text-xl font-bold">{title}</h1>
        {subtitle && (
          <p className="mt-0.5 text-xs text-slate-600">{subtitle}</p>
        )}
        <p className="mt-1 text-[10px] text-slate-500">
          Practicum Evaluation Portal · Generated {generatedLabel}
        </p>
      </div>

      {/* Summary stats box */}
      <div className="grid grid-cols-3 gap-3 rounded border border-slate-300 p-3 text-sm">
        {derivedStats.map((s) => (
          <div key={s.label}>
            <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
              {s.label}
            </p>
            <p className="text-base font-bold tabular-nums">{s.value}</p>
          </div>
        ))}
      </div>

      {/* Per-student sections */}
      {rows.length === 0 ? (
        <p className="py-4 text-center text-sm text-slate-500">
          No time log sessions on record.
        </p>
      ) : (
        rows.map(({ student, companyName, supervisorName, sessions }) => (
          <StudentTimeSection
            key={student.id}
            student={student}
            companyName={companyName}
            supervisorName={supervisorName}
            sessions={sessions}
          />
        ))
      )}

      {/* Footer */}
      <div className="mt-6 grid grid-cols-2 gap-6 pt-4 text-xs text-slate-500">
        <div>
          <p>Coordinator / Supervisor signature</p>
          <div className="mt-6 border-t border-slate-400" />
        </div>
        <div>
          <p>Date</p>
          <div className="mt-6 border-t border-slate-400" />
        </div>
      </div>
      <div className="flex items-center gap-1.5 text-[10px] text-slate-500">
        <Clock className="h-3 w-3" />
        Generated by Practicum Evaluation Portal · Time Log Report
      </div>
    </div>
  );
}

// ============================================================
// Per-student section (with weekly grouping + subtotals)
// ============================================================

function StudentTimeSection({
  student,
  companyName,
  supervisorName,
  sessions,
}: {
  student: Student;
  companyName?: string;
  supervisorName?: string;
  sessions: TimeLog[];
}) {
  // Group completed sessions by week (Monday-based), oldest first.
  const completed = sessions
    .filter((t) => t.clockOutAt !== null && t.durationMs)
    .sort((a, b) => (a.clockInAt < b.clockInAt ? -1 : 1));

  const weeklyGroups = React.useMemo(() => {
    const map = new Map<string, TimeLog[]>();
    for (const t of completed) {
      const k = weekKey(t.clockInAt);
      if (!map.has(k)) map.set(k, []);
      map.get(k)!.push(t);
    }
    return Array.from(map.entries()).map(([key, logs]) => ({
      key,
      label: weekLabelFromKey(key),
      logs,
      subtotalMs: logs.reduce((s, t) => s + (t.durationMs ?? 0), 0),
    }));
  }, [completed]);

  const totalMs = completed.reduce((s, t) => s + (t.durationMs ?? 0), 0);
  const totalHours = totalMs / 3600_000;
  const pct =
    student.requiredHours > 0
      ? Math.min(100, Math.round((totalHours / student.requiredHours) * 100))
      : 0;
  const remaining = Math.max(0, student.requiredHours - totalHours);

  return (
    <div className="break-inside-avoid border border-slate-200 p-3">
      {/* Student header */}
      <div className="mb-2 flex items-baseline justify-between border-b border-slate-100 pb-1.5">
        <div>
          <p className="text-sm font-semibold">{student.name}</p>
          <p className="text-[10px] text-slate-500">
            {student.studentNumber} · {student.course}
            {companyName ? ` · ${companyName}` : ""}
            {supervisorName ? ` · Supervisor: ${supervisorName}` : ""}
          </p>
        </div>
        <div className="text-right text-[10px] text-slate-600">
          <p>
            Tracked:{" "}
            <strong className="tabular-nums">{totalHours.toFixed(1)}h</strong> /{" "}
            {student.requiredHours}h ({pct}%)
          </p>
          <p>
            Remaining:{" "}
            <strong className="tabular-nums">{remaining.toFixed(1)}h</strong>
          </p>
        </div>
      </div>

      {completed.length === 0 ? (
        <p className="py-2 text-center text-[11px] italic text-slate-500">
          No completed sessions on file.
        </p>
      ) : (
        <table className="w-full border-collapse text-[11px]">
          <thead>
            <tr className="border-b border-slate-200 text-left text-slate-500">
              <th className="py-1 pr-2">Date</th>
              <th className="py-1 pr-2">Clock In</th>
              <th className="py-1 pr-2">Clock Out</th>
              <th className="py-1 pr-2 text-right">Duration</th>
            </tr>
          </thead>
          <tbody>
            {weeklyGroups.map((group) => (
              <React.Fragment key={group.key}>
              {/* Week group header row */}
              <tr className="border-b border-slate-200 bg-slate-50">
                  <td
                    colSpan={4}
                    className="py-1 px-2 text-[10px] font-bold uppercase tracking-wide text-slate-600"
                  >
                    {group.label} · {group.logs.length} session
                    {group.logs.length === 1 ? "" : "s"}
                  </td>
                </tr>
                {group.logs.map((t) => (
                  <tr key={t.id} className="border-b border-slate-100">
                    <td className="py-1 pr-2">{formatDate(t.clockInAt)}</td>
                    <td className="py-1 pr-2 tabular-nums">
                      {formatTime(t.clockInAt)}
                    </td>
                    <td className="py-1 pr-2 tabular-nums">
                      {formatTime(t.clockOutAt)}
                    </td>
                    <td className="py-1 pr-2 text-right font-medium tabular-nums">
                      {formatDuration(t.durationMs ?? 0)}
                    </td>
                  </tr>
                ))}
                {/* Weekly subtotal */}
                <tr className="border-b border-slate-200 bg-slate-50/60 font-semibold">
                  <td className="py-1 pr-2 text-[10px] uppercase tracking-wide text-slate-500" colSpan={3}>
                    Subtotal
                  </td>
                  <td className="py-1 pr-2 text-right tabular-nums">
                    {formatDuration(group.subtotalMs)}
                  </td>
                </tr>
              </React.Fragment>
            ))}
            {/* Grand total */}
            <tr className="border-t-2 border-slate-400 font-bold">
              <td className="py-1.5 pr-2 text-[10px] uppercase tracking-wide text-slate-600" colSpan={3}>
                Grand Total · {completed.length} session
                {completed.length === 1 ? "" : "s"}
              </td>
              <td className="py-1.5 pr-2 text-right tabular-nums">
                {formatDuration(totalMs)}
              </td>
            </tr>
          </tbody>
        </table>
      )}
    </div>
  );
}

export default TimeLogReportDocument;
